speed up setup time by conditionally loading nvim-treesitter.query and nvim-treesitter.indent
lukas-reineke/indent-blankline.nvim pull request #213
Opened 2021-09-09 09:40 UTC by goolord

according to `PackerProfile` this change makes `setup` go from taking ~22ms to ~0.4ms on my machine. unsure why requiring these files is so slow. 

this change in its current (initial) state would break a buffer local `indent_blankline_use_treesitter` option, but i couldn't figure out a way to make it not without calling `require` in `refresh`, which seems bad.

2021-09-09 09:45 UTC, goolord commented
the effect is less dramatic without using https://github.com/lewis6991/impatient.nvim
(~6ms -> ~2ms), so I'll report it there as well

2021-09-09 16:51 UTC, goolord commented on lua/indent_blankline/init.lua
> +local ts_query = nil
having this at the top level is the only thing that prevents `require` from having to be called each refresh

2021-09-09 16:56 UTC, goolord commented on lua/indent_blankline/init.lua
> +            require("nvim-treesitter.indent")
still needed for `get_indent`?

2021-09-10 02:32 UTC, lukas-reineke commented on lua/indent_blankline/init.lua
> +local ts_query = nil
`require` is cached, you can safely call this every time.

2021-09-10 02:33 UTC, lukas-reineke commented on lua/indent_blankline/init.lua
> +            require("nvim-treesitter.indent")
of course, I was confused with the code that didn't assign it to anything.

2021-09-10 09:03 UTC, lukas-reineke requested changes

2021-09-10 09:03 UTC, lukas-reineke commented on lua/indent_blankline/init.lua
> +        use_ts_indent = ts_query.has_indents(vim.bo.filetype)
```suggestion
    local ts_indent
    if v("indent_blankline_use_treesitter") then
        local ts_query_status, ts_query = pcall(require, "nvim-treesitter.query")
        local ts_indent_status
        ts_indent_status, ts_indent = pcall(require, "nvim-treesitter.indent")
        use_ts_indent = ts_query_status and ts_indent_status and ts_query.has_indents(vim.bo.filetype)
```

`ts_query` can be inside the if block.
And you still need to check the status of the `require`

2021-09-10 22:52 UTC, lukas-reineke approved these changes
Thanks

2021-09-10 22:53 UTC, lukas-reineke commented
oh sorry, can you please rebase against develop and fix the conflictc

2021-09-10 23:47 UTC, lukas-reineke approved these changes

2021-09-11 13:13 UTC, lukas-reineke commented
@goolord you need to rebase, not merge in develop.
I want the project to have a linear history.
You need to run `git rebase develop`

2021-09-11 19:13 UTC, goolord commented
can't you just squash these commits? it's really only one change logically

2021-09-12 02:31 UTC, lukas-reineke approved these changes
:tada:

2021-09-12 02:31 UTC, merged