Context highlight list
lukas-reineke/indent-blankline.nvim pull request #68
Opened 2021-03-23 07:32 UTC by rhino1998

This PR adds a list for defining different highlights at different levels with context highlighting. Currently there is no synchronization between brace/paren/other scope delimiter and the indent line color. It is just coincidental that the colors of the braces and the line match in the second image.

![image](https://user-images.githubusercontent.com/9094640/112109347-d4162900-8b87-11eb-9e2b-58e2aae09ea1.png)
![image](https://user-images.githubusercontent.com/9094640/112109377-e1cbae80-8b87-11eb-81e9-2a72b51d1d88.png)

2021-03-23 08:25 UTC, lukas-reineke requested changes
Looks good, Thank you.

You are missing one instance of `context_highlight` for trailing indent on line 112
You'll need to calculate the index with `math.ceil(#virtual_text / 2) + 1)`

2021-03-23 08:25 UTC, lukas-reineke commented on doc/indent_blankline.txt
> +        let g:indent_blankline_context_highlight = 'Error'
example is wrong

2021-03-23 19:08 UTC, rhino1998 commented on doc/indent_blankline.txt
> +        let g:indent_blankline_context_highlight = 'Error'
oh, woops, fixed

2021-03-25 02:15 UTC, lukas-reineke approved these changes
Thank you

2021-03-25 02:15 UTC, merged