feat: repeat indent guides on wrapped lines with 'breakindent'
lukas-reineke/indent-blankline.nvim pull request #810
Opened 2023-12-25 15:30 UTC by luukvbaal

Opt-out with ibl.config.indent.repeat_linebreak = false.

Close #577

2023-12-25 15:31 UTC, luukvbaal commented
Depends on https://github.com/neovim/neovim/pull/26625

2023-12-26 00:24 UTC, lukas-reineke commented
Thanks, this is nice.

> may be replaced with a version check at some point I suppose.

Yeah, version check would be cleaner.

> One caveat here is that since extmarks are local to a buffer, and 'breakindent' is a window option, the indent lines may overlap buffer text when there are multiple windows with different 'breakindent' values displaying the same buffer... Doubt that is a real issue though.

This is fine, there are other option values with the same restriction already. I have this helper function to get the right window ID to use with `nvim_get_option_value`. Please use that as well.
https://github.com/lukas-reineke/indent-blankline.nvim/blob/0dca9284bce128e60da18693d92999968d6cb523/lua/ibl/utils.lua#L131-L142

And please add the option to the docs as well.

2023-12-26 13:30 UTC, luukvbaal commented
Hmm there is another caveat. Depending on the value of `'breakindentopt'`, we may still end up placing the indent guide virtual text over the actual buffer text. Not sure how to handle that TBH, here or in the nvim API.

2023-12-26 13:39 UTC, lukas-reineke requested changes
Just one small comment, rest looks good now

2023-12-26 13:39 UTC, lukas-reineke commented on doc/indent_blankline.txt
> +                         if 'breakindent' is set
This way it links to the `breakindent` docs
```suggestion
                         if |'breakindent'| is set
```

2023-12-26 13:44 UTC, lukas-reineke commented on lua/ibl/config.types.lua
> +---@field repeat_linebreak boolean
This has to be optional, that's also the reason the LSP tests fail.
```suggestion
---@field repeat_linebreak boolean?
```

2023-12-26 13:44 UTC, lukas-reineke commented
I will think about how to handle `breakindentopt` correctly. It's pretty niche, I'm okay with just not supporting this for now.

2023-12-26 13:47 UTC, luukvbaal commented
> I will think about how to handle `breakindentopt` correctly. It's pretty niche, I'm okay with just not supporting this for now.

That's my feeling as well. I'll address the comments/CI failure later.

2023-12-26 23:53 UTC, lukas-reineke approved these changes
thank you :rocket:

2023-12-26 23:53 UTC, merged

2023-12-27 22:35 UTC, mehalter commented
Should this be on by default? It seems like having the default options require the latest Neovim nightly is a bad idea even if the user can opt out of the new feature. It seems like it should be an opt in

2023-12-27 23:23 UTC, luukvbaal commented
Whether an option requires a certain Neovim version seems irrelevant to the option's default value. I think most people will want this option enabled, that's why I suggested opt out.

I do agree that just checking for `has("neovim-0.10")` is more disruptive than it has to be for  for people on a nightly version, but not the latest nightly. But they are using a nightly version, they can just update which I suppose was @lukas-reineke's view :)

2023-12-27 23:29 UTC, mehalter commented
Yeah I agree. I'll be honest, I just saw in the docs that the default is true and I didn't notice the check for 0.10. this is a completely sane default and relying on people using nightly to just update makes sense for me! People using nightly accept the chance for bugs and potentially infinite amounts of instability 😂

2023-12-27 23:32 UTC, lukas-reineke commented
The option will simply be ignored if you are on stable.
And if you are on nightly, it's your responsibility to be up to date.